ALTER TABLE session ADD INDEX index_on_value(value);
ALTER TABLE user ADD INDEX index_on_user_id(user_id);
ALTER TABLE group_info ADD INDEX index_on_group_id(group_id);
ALTER TABLE group_member ADD INDEX index_on_user_id(user_id);
ALTER TABLE record_last_access ADD INDEX index_on_id(user_id, record_id);
ALTER TABLE category ADD INDEX index_on_category_id(category_id);
ALTER TABLE category_group ADD INDEX index_on_group_id(group_id);
ALTER TABLE file ADD INDEX index_on_file_id(file_id);
ALTER TABLE record ADD INDEX index_on_record_id(record_id);
ALTER TABLE record_item_file ADD INDEX index_on_lr_id(linked_record_id);
ALTER TABLE record_comment ADD INDEX index_on_lr2_id(linked_record_id);
